### ISSUE TITLE
List of failed compiles

### ISSUE THREAD

**Issue by jvcleave** [andreasmuller/RaspberryPiWorkshop#1]
just dumping this here for now - some results of the buildAll.sh script

```
Makefile:13: ../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make: No such file or directory
make: *** No rule to make target `../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make'.  Stop.

StandaloneTimingServer


Makefile:13: ../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make: No such file or directory
make: *** No rule to make target `../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make'.  Stop.

 dev_MultiScreenCommonTiming  compile FAILED 


 Makefile:13: ../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make: No such file or directory
make: *** No rule to make target `../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make'.  Stop.

 dev_MultipleViewpointTransformOffsets  compile FAILED 

 Makefile:13: ../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make: No such file or directory
make: *** No rule to make target `../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make'.  Stop.

 dev_ShaderLiveCodingExample  compile FAILED 


Makefile:13: ../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make: No such file or directory
make: *** No rule to make target `../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make'.  Stop.

 dev_StandaloneTimingServer  compile FAILED 


In file included from addons/ofxOMXPlayer/src/ofxOMXPlayer.cpp:10:0:
addons/ofxOMXPlayer/src/ofxOMXPlayer.h:12:17: fatal error: RBP.h: No such file or directory
compilation terminated.
distcc[12721] ERROR: compile addons/ofxOMXPlayer/src/ofxOMXPlayer.cpp on localhost failed
make[1]: *** [obj/linuxarmv6l/Release/addons/ofxOMXPlayer/src/ofxOMXPlayer.o] Error 1
make: *** [Release] Error 2

 dev_VideoShaderLiveCoding  compile FAILED 
```

**Comment by andreasmuller** [comment]
Should be taken care of now, the standalone timing server was the only one
that had not been superseded by a non dev_ example.

/A

On Monday, March 11, 2013, Jason Van Cleave wrote:

> just dumping this here for now - some results of the buildAll.sh script
> 
> Makefile:13: ../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make: No such file or directory
> make: **\* No rule to make target `../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make'.  Stop.
> 
> StandaloneTimingServer
> 
> Makefile:13: ../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make: No such file or directory
> make: **\* No rule to make target `../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make'.  Stop.
> 
>  dev_MultiScreenCommonTiming  compile FAILED
> 
>  Makefile:13: ../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make: No such file or directory
> make: **\* No rule to make target `../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make'.  Stop.
> 
>  dev_MultipleViewpointTransformOffsets  compile FAILED
> 
>  Makefile:13: ../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make: No such file or directory
> make: **\* No rule to make target `../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make'.  Stop.
> 
>  dev_ShaderLiveCodingExample  compile FAILED
> 
> Makefile:13: ../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make: No such file or directory
> make: **\* No rule to make target `../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make'.  Stop.
> 
>  dev_StandaloneTimingServer  compile FAILED
> 
> In file included from addons/ofxOMXPlayer/src/ofxOMXPlayer.cpp:10:0:
> addons/ofxOMXPlayer/src/ofxOMXPlayer.h:12:17: fatal error: RBP.h: No such file or directory
> compilation terminated.
> distcc[12721] ERROR: compile addons/ofxOMXPlayer/src/ofxOMXPlayer.cpp on localhost failed
> make[1]: **\* [obj/linuxarmv6l/Release/addons/ofxOMXPlayer/src/ofxOMXPlayer.o] Error 1
> make: **\* [Release] Error 2
> 
>  dev_VideoShaderLiveCoding  compile FAILED
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/andreasmuller/RaspberryPiWorkshop/issues/1
> .

## 

ø¤°`°¤ø,¸¸¸,ø¤°`°¤ø,¸¸»«¸,ø¤°`°¤ø,¸

 Nanika

 p:  +44.(0)20.7729.3090
 f:  +44.(0)20.7729.3396

 t:  @nanikawa

 http://www.nanikawa.com

ø¤°`°¤ø,¸¸¸,ø¤°`°¤ø,¸¸»«¸,ø¤°`°¤ø,¸
